nativ1/fakture/urls.py
from django.urls import path
from . import views

app_name = 'fakture'

urlpatterns = [
    path('', views.pocetna_stranica, name='index'),
    path('pdf/<str:pk>/', views.pdf_generator, name='pdf1'),
    path('kreiranje-fakture/', views.KreirajFakturu.as_view(), name='kreiraj-fakturu'),
    path('kreiranje-fakture/<int:pk>/prodaja/', views.KreirajFakturuProdaja.as_view(), name='faktura-prodaja'),
    path('kreiranje-fakture/prodaja/<int:pk>/', views.faktura_skica_gotova, name='faktura-skica'),
    path('kreiranje-fakture/prodaja/<int:pk>/detalji/', views.ProdajaDetalji.as_view(), name='prodaja-detalji'),
    path('kreiranje-fakture/prodaja/<int:pk>/izmjena/', views.ProdajaIzmjena.as_view(), name='prodaja-izmjena'),
    path('kreiranje-fakture/prodaja/<int:pk>/brisanje/', views.ProdajaBrisanje.as_view(), name='prodaja-brisanje'),
    path('kreiranje-fakture/<int:pk>/izmjena/', views.FakturaUpdate.as_view(), name='faktura-izmjena'),
    path('kreiranje-fakture/izmjena/<int:pk>/prodaja/', views.ProdajaGlavnaUpdate.as_view(), name='faktura-prodaja-izmjena'),
    path('lista_faktura/', views.FaktureLista.as_view(), name='lista_fakturi'),
    path('kupci/', views.KupciLista.as_view(), name='lista-kupci'),
    path('lista_faktura/<int:pk>/', views.FaktureDetail.as_view(), name='faktura-detalji'),
    path('kupci/novi-kupac/', views.KupacNovi.as_view(), name='kupac-novi'),
    path('kupac/<int:pk>/', views.KupacDetalji.as_view(), name='kupac-detalji'),
    path('kupac/<int:pk>/update/', views.KupacUpdate.as_view(), name='kupac-update'),
    path('base-nativ/', views.base, name='base-nativ'),
    path('valute/', views.KreirajValute.as_view(), name='kreiraj-valutu'),
    path('<int:pk>/', views.ValuteUpdate.as_view(), name='valute_update'),
    path('pozicije-lista/', views.PozicijaLista.as_view(), name='pozicije-lista'),
    #path('usluge-lista/kreiraj-uslugu/', views.UslugaKreiraj.as_view(), name='usluge-kreiraj'),
    #path('usluge-lista/kreiraj-uslugu/<int:pk>/update/', views.UslugaUpdate.as_view(), name='usluge-update'),
    path('pozicija/kreiraj/', views.PozicijaKreiraj.as_view(), name='pozicije-kreiraj'),
    path('pozicija/kreiraj/<int:pk>/update/', views.PozicijaUpdate.as_view(), name='pozicija-update'),
    path('lista_faktura/godine/<str:year>/', views.faktura_po_godinama, name='fakture_po_godinama'),
    path('lista_ponuda/', views.PonudaLista.as_view(), name='ponuda-lista'),
    path('lista_ponuda/<int:pk>/', views.PonudaDetail.as_view(), name='ponuda-detalji'),
    path('ponuda-create/', views.KreirajPonudu.as_view(), name='ponuda-create'),
    path('ponuda-create/<int:pk>/ponuda-prodaja/', views.KreirajPonuduProdaja.as_view(), name='ponuda-prodaja'),
    path('ponuda-create/ponuda-prodaja/<int:pk>/detalji/', views.ProdajaPonudaDetalji.as_view(), name='ponuda-prodaja-detalji'),
    path('ponuda-create/prodaja-ponuda/<int:pk>/', views.ponuda_skica_gotova, name='ponuda-skica'),
    path('ponuda-pdf/<str:pk>/', views.pdf_generator_ponuda, name='ponuda-pdf'),
    path('ponuda-create/<int:pk>/izmjena/', views.PonudaUpdate.as_view(), name='ponuda-izmjena'),
    path('ponuda-create/prodaja/<int:pk>/brisanje/', views.PonudaProdajaBrisanje.as_view(), name='ponuda-prodaja-brisanje'),
    path('ponuda-create/prodaja/<int:pk>/izmjena/', views.PonudaProdajaIzmjena.as_view(), name='ponuda-prodaja-izmjena'),
    path('usluge-lista/<str:year>/', views.ponude_po_godinama, name='ponude_po_godinama'),
    path('pdf-lista/', views.MojiPDF.as_view(), name='lista-pdf-files'),
    path('placene-fakture/', views.pregled_placenih_faktura_godine, name='placene-fakture-godine'),
    path('placene-fakture/<int:year>/', views.pregled_placenih_faktura, name='placene-fakture'),
    path('placene-fakture/update/<int:pk>/', views.FakturePlaceneUpdate.as_view(), name='placene-fakture-update'),
    path('excel/<int:year>/', views.export_users_xls, name='export-excel'),
    path('ponuda-u-fakturu/<int:pk>', views.ponuda_u_fakturu, name='ponuda-u-fakturu'),
    path('realizacija-ponuda/<int:pk>/', views.ponuda_storno, name='ponuda-storniranje'),
]

nativ1/nativ1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('fakture/', include('fakture.urls')),
    path('', RedirectView.as_view(url='fakture/')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [ path('accounts/', include('django.contrib.auth.urls'))]

nativ1/fakture/views.py
from django.shortcuts import render

# Create your views here.
import os
from django.conf import settings
from os import listdir
from os.path import isfile, join
from weasyprint import HTML, CSS
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, ListView, UpdateView, DetailView, CreateView, DeleteView, TemplateView
from django.db.models import Sum, Q
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from .models import Korisnik, Kupac, Faktura, Prodaja, Pozicija, Valute, Ponuda, ProdajaPonuda
from django.template.loader import get_template, render_to_string
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from .forms import FakturaForma, ProdajaForma, PonudaForma, PonudaProdajaForma, FakturaUpdateForm, FakturaUpdateFormPlaceno
from django.utils.dateformat import DateFormat
from django.core.files.base import ContentFile
import xlwt, xlsxwriter, io
import datetime


def pdf_generator(request, pk):
    faktura = Faktura.objects.get(id=pk)
    prodaja = Prodaja.objects.filter(faktura__id=pk)
    prodaja_do_8 = Prodaja.objects.filter(faktura__id=pk)[:8]
    prodaja_8 = Prodaja.objects.filter(faktura__id=pk)[8:]
    prodaja_do_16 = Prodaja.objects.filter(faktura__id=pk)[8:24]
    prodaja_16 = Prodaja.objects.filter(faktura__id=pk)[24:]
    neto_suma = Prodaja.objects.filter(faktura__id=pk).aggregate(net_suma=Sum('neto_cijena'))
    bruto_suma = Prodaja.objects.filter(faktura__id=pk).aggregate(brt_suma=Sum('bruto_cijena'))
    formatirano1= round(neto_suma['net_suma'], 2)
    formatirano = round(bruto_suma['brt_suma'], 2)
    bruto_suma['brt_suma'] = formatirano
    neto_suma['net_suma'] = formatirano1
    prodaja_count = len(prodaja)
    korisnik = Korisnik.objects.get(username=request.user.username)
    valuta = Valute.objects.get(valute='EUR')
    avans = faktura.avansno_uplaceno
    bruto_suma_avans = bruto_suma['brt_suma'] - avans
    bruto_razlika = bruto_suma['brt_suma'] -  neto_suma['net_suma']
    image = settings.STATIC_ROOT+'slike/logo_nativ.png'
    valuta_bam = Valute.objects.get(valute='BAM')
    bruto_suma_bam = round(bruto_suma['brt_suma'] * valuta_bam.bam_evro, 2)
    datum = DateFormat(faktura.datum_fakture)
    datum1 = datum.format('Ymd')
    count = 0
    pdv = []
    for p in prodaja:
        pdv.append(p.pdv)
        count += 1
        if count == 1:
            break;
    faktura.pdf.delete()
    context = {
        'korisnik': korisnik,
        'faktura': faktura,
        'prodaja': prodaja,
        'prodaja_5': prodaja[4:],
        'prodaja_24_40':prodaja[24:40],
        'prodaja_40_52':prodaja[40:52],
        'prodaja_8': prodaja_8,
        'prodaja_do_8': prodaja_do_8,
        'prodaja_do_16': prodaja_do_16,
        'prodaja_16': prodaja_16,
        'neto_suma': neto_suma,
        'bruto_suma': bruto_suma,
        'm': '1111',
        'prodaja_count': prodaja_count,
        'valuta':valuta,
        'avans': avans,
        'bruto_avans':bruto_suma_avans,
        'bruto_razlika': bruto_razlika,
        'image': image,
        'bruto_suma_bam': bruto_suma_bam,
        'valute_bam': valuta_bam,
        'pdv': pdv[0],

    }



    html_template = render_to_string('fakture/faktura_html.html', context)
    instance = get_object_or_404(Faktura.objects.filter(pk=pk))

    pdf_file = HTML(string=html_template,  base_url = request.build_absolute_uri()).write_pdf(stylesheets=[CSS(settings.STATIC_ROOT + 'css/style.css')],  presentational_hints=True)
    response = HttpResponse(pdf_file, content_type='application/pdf')
    response['Content-Disposition'] = 'filename="Faktura broj: IN-{}-{}-{}.pdf"'.format(faktura.broj_fakture, datum1, faktura.ident_brojevi)
    pdf =ContentFile(pdf_file)
    if not instance.pdf:
        instance.pdf.save('IN-{}-{}-{}.pdf'.format(faktura.broj_fakture, datum1, faktura.ident_brojevi), pdf)
    return response




@login_required
#@permission_required
def pocetna_stranica(request):
    context = {}

    if Faktura.objects.filter(broj_fakture__isnull=True):
        pass
    else:
        fakture = Faktura.objects.filter(broj_fakture__isnull=False).order_by('-broj_fakture')
        #datum = Faktura.objects.values(Year=TruncYear('datum_fakture')).distinct()
        datum = Faktura.objects.dates('datum_fakture', 'year')
        valute = Valute.objects.all().order_by('valute')

        context = {
            'fakture':fakture,
            'datum':datum,
            'valute': valute,


        }

    return render(request, 'bazni_template.html', context)

def base(request):
    return render(request, 'fakture/base_nativ.html', {})

class KreirajValute(LoginRequiredMixin, CreateView):
    model = Valute
    fields = '__all__'
    template_name = 'fakture/valute_create.html'
    success_url = reverse_lazy('fakture:kreiraj-valutu')

    def get_context_data(self, *args, **kwargs):
        context = super(KreirajValute, self).get_context_data(**kwargs)
        context['valute'] = Valute.objects.all().order_by('valute')
        return context

class ValuteUpdate(LoginRequiredMixin, UpdateView):
    model = Valute
    fields = ('bam_evro',)
    template_name = 'fakture/valuta_update.html'

    def get_success_url(self):
        return reverse_lazy('fakture:index')

class FaktureLista(LoginRequiredMixin, ListView):
    model = Faktura
    template_name = 'fakture/faktura_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(FaktureLista, self).get_context_data(**kwargs)
        context['datum'] = Faktura.objects.dates('datum_fakture', 'year')
        context['valute'] = Valute.objects.all()
        context['kupci'] = Kupac.objects.all()
        context['pozicije'] = Pozicija.objects.all()
        return context

class FaktureDetail(LoginRequiredMixin, DetailView):
    model = Faktura
    template_name = 'fakture/fakture_detail.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(FaktureDetail, self).get_context_data(**kwargs)
        bf = Faktura.objects.get(id=self.kwargs['pk'])
        proodaja = Prodaja.objects.filter(faktura_id=bf)
        context['faktura'] = Faktura.objects.get(id=self.kwargs['pk'])
        context['datum'] = Faktura.objects.dates('datum_fakture', 'year')
        context['pozicije'] = Pozicija.objects.all()
        context['prodaja'] = proodaja
        return context

@login_required
def faktura_po_godinama(request, year):
    fakture = Faktura.objects.filter(datum_fakture__year=year)

    return render(request, 'fakture/godina_fakture.html', {'fakture':fakture})

class KreirajFakturu(LoginRequiredMixin, CreateView):
    model = Faktura
    form_class = FakturaForma
    template_name = 'fakture/faktura_create.html'
    success_url = reverse_lazy('fakture:faktura-prodaja')

    def get_initial(self):
        if not Faktura.objects.filter(broj_fakture__isnull=False).exists():
            faktura = '0001'
            return {'broj_fakture': faktura}
        else:
            broj = Faktura.objects.filter(broj_fakture__isnull=False).order_by('-pk')[0]
            faktura1 = int(broj.broj_fakture)
            if faktura1 <= 9:
                faktura = '000'+ str(faktura1+1)
                return {'broj_fakture': faktura}
            elif 10 <= faktura1 <= 99:
                faktura = '00' + str(faktura1+1)
                return {'broj_fakture': faktura}
            elif 100 <= faktura1 <= 999:
                faktura = '0'+str(faktura1+1)
                return {'broj_fakture': faktura}
    def get_context_data(self, **kwargs):
        context = super(KreirajFakturu, self).get_context_data(**kwargs)
        context['valute'] = Valute.objects.all()
        context['kupci'] = Kupac.objects.all()
        context['pozicije'] = Pozicija.objects.all()
        return context

    def get_success_url(self):
        return reverse('fakture:faktura-prodaja', args={self.object.pk})



class KreirajFakturuProdaja(LoginRequiredMixin, CreateView):
    form_class = ProdajaForma
    template_name = 'fakture/faktura_create_nastavak.html'
    success_url = reverse_lazy('fakture:faktura-prodaja')
    def get_initial(self, **kwargs):
        if Faktura.objects.filter(broj_fakture__isnull=True):
            faktura = '0001'
        else:
            broj = Faktura.objects.get(id=self.kwargs['pk'])
            faktura = broj
        return {'faktura':faktura}

    def get_context_data(self, **kwargs):
        context = super(KreirajFakturuProdaja, self).get_context_data(**kwargs)
        faktura = Faktura.objects.get(id=self.kwargs['pk'])
        neto_suma = Prodaja.objects.filter(faktura_id=faktura.pk).aggregate(net_suma=Sum('neto_cijena'))
        bruto_suma = Prodaja.objects.filter(faktura__id=faktura.pk).aggregate(brt_suma=Sum('bruto_cijena'))

        context['faktura']= Faktura.objects.get(id=self.kwargs['pk'])
        context['prodaja'] = Prodaja.objects.all().filter(faktura__id=faktura.pk)
        context['neto_suma'] = neto_suma
        context['bruto_suma'] = bruto_suma
        context['pozicije'] = Pozicija.objects.all()
        return context
    def get_success_url(self):
        return reverse('fakture:faktura-prodaja', kwargs={'pk':self.object.faktura.pk})

class ProdajaDetalji(LoginRequiredMixin, DetailView):
    model = Prodaja
    template_name = 'fakture/prodaja_detail.html'
    def get_success_url(self):
        return reverse('fakture:faktura-prodaja', args={self.object.pk})

class ProdajaIzmjena(LoginRequiredMixin, UpdateView):
    model = Prodaja
    fields = '__all__'
    template_name = 'fakture/update_prodaja.html'
    def get_success_url(self):
        return reverse('fakture:faktura-prodaja', kwargs={'pk':self.object.faktura.pk})

class FakturaUpdate(LoginRequiredMixin, UpdateView):
    model = Faktura
    form_class = FakturaUpdateForm

nativ1/fakture/templates/fakture/faktura_list.html
{% extends 'fakture/base_nativ.html' %}
{% load static %}
{% block fakture %}
    {% if pozicije and valute and kupci %}
    {% else %}
    <p style="color: darkred; font-size: 20px; font-weight: bold">Vratite se na početnu stranu i unesite minimalno po jedan element u tabele Pozicije, Valute i Kupci!</p>
    {% endif %}
    {% if datum %}
    {% for d in datum %}
         <div class="fakture-lista-naslovna">
    <h2>Fakture za {{ d|date:'Y' }} godinu</h2>
    <ul>
    {% for faktura in faktura_list %}
          {% if d|date:'Y' == faktura.datum_fakture|date:'Y' %}
                  <li><a href="{% url 'fakture:faktura-detalji' faktura.pk %}">Broj fakture {{ faktura.broj_fakture }}</a>;  {{ faktura.kupac }} -- Datum fakture {{ faktura.datum_fakture|date:'d-m-Y' }} </li>

              {% endif %}
    {% endfor %}
    </ul>
         </div>
    {% endfor %}
{% else %}
<h3>U bazi trenutno nema kreiranih faktura!</h3>
{% endif %}
{% endblock %}
{% block fakture_godine %}
    {% if datum %}
        <div class="fakture-godine">
        <h2>Fakture po godinama</h2>
        {% for d in datum %}
        <p><a href="{% url 'fakture:fakture_po_godinama' d|date:'Y' %}">Fakture za {{ d|date:'Y' }} godinu</a></p>
        {% endfor %}
    </div>
    {% else %}
{% endif %}
{% endblock %}
{% block faktura_button %}
    <div>
    <p>Kreiraj novu fakturu: </p>
    <form>
        <button formaction="{% url 'fakture:kreiraj-fakturu' %}">Kreiraj</button>
    </form>
    </div>
{% endblock %}

nativ1/fakture/templates/fakture/fakture_detail.html
{% extends 'fakture/base_nativ.html' %}
{% load static %}
{% block fakture %}
    {% if pozicije %}
    {% else %}
    <p style="color: darkred; font-size: 20px; font-weight: bold">Vratite se na početnu stranu i unesite minimalno po jedan element u tabelu Pozicije!</p>
    {% endif %}
    {% if datum %}

         <div class="fakture-lista-naslovna">
    <h2>Fakture za {{ d|date:'Y' }} godinu</h2>
    <p>Broj fakture: IN-{{ faktura.broj_fakture }}-{{ faktura.datum_fakture|date:'Ymd' }}-{{ faktura.ident_brojevi }}</p>
         <p>Datum fakture: {{ faktura.datum_fakture|date:'d-m-Y' }}</p>
         <p>Kupac: {{ faktura.kupac }}</p>
         <p>Rok plaćanja: {{ faktura.rok_placanja|date:'d-m-Y' }}</p>
         {% if faktura.pdf %}
         <p>Download pdf: <a href="/media/{{ faktura.pdf }}" download="{{ faktura.pdf }}">PDF</a> </p>
         {% endif %}
         {% if not prodaja %}
             <p style="font-weight: bold; font-size: 25px; color: darkred">U fakturi nemate unešene usluge!</p>
             <form>
             <button formaction="{% url 'fakture:faktura-izmjena' faktura.pk %}">Unesite elemente</button>
             </form>
         {% else %}
             <form>
             <button formaction="{% url 'fakture:faktura-skica' faktura.pk %}">Faktura-skica</button>
             </form>
         {% endif %}
         </div>

{% else %}
<h3>U bazi trenutno nema kreiranih faktura!</h3>
{% endif %}
{% endblock %}

{% block faktura_button %}
    <div>
    <p>Kreiraj novu fakturu: </p>
    <form>
        <button formaction="{% url 'fakture:kreiraj-fakturu' %}">Kreiraj</button>
    </form>
    </div>
{% endblock %}

nativ1/fakture/templates/fakture/kupac_izmjeni.html
{% extends 'fakture/base_nativ.html' %}
{% block fakture %}
    <form method="post" action="">
{% csrf_token %}
    <table>
{{ form.as_table }}
        </table>
<input type="submit" value="Spasi promjene">
        </form>
    <br>
        <form>
        <button formaction="{% url 'fakture:lista-kupci' %}">Vrati se bez promjena</button>
            </form>
{% endblock %}

nativ1/fakture/templates/fakture/kupac_list.html
{% extends 'fakture/base_nativ.html' %}
{% block fakture %}
    {% if kupac_list %}
    {% for z in zemlja %}
        <div class="fakture-lista-naslovna">
        <h2>Država {{ z.drzava }}</h2>
        <ul>
            {% for k in kupac_list %}
        {% if k.drzava == z.drzava %}
            <li>Ime i prezime kupca: {{ k.ime }} {{ k.prezime }}, Naziv preduzeća: {{ k.naziv_firme }}, Drzava: {{ k.drzava }}, <a href="{% url 'fakture:kupac-detalji' k.pk %}">Izmjeni podatke</a></li>
                {% endif %}
                {% endfor %}
                </ul>
        </div>


    {% endfor %}
        {% else %}
        <h2>Trenutno u bazi nema unešenih kupaca!</h2>
    {% endif %}

{% endblock %}
    {% block faktura_button %}
    <div>
    <p>Kreiraj novog kupca: </p>
    <form>
        <button formaction="{% url 'fakture:kupac-novi' %}">Kreiraj</button>
    </form>
    </div>
{% endblock %}

nativ1/fakture/templates/fakture/ponuda_detail.html
{% extends 'fakture/base_nativ.html' %}
{% load static %}
{% block fakture %}
    {% if pozicije %}
    {% else %}
    <p style="color: darkred; font-size: 20px; font-weight: bold">Vratite se na početnu stranu i unesite minimalno po jedan element u tabelu Pozicije!</p>
    {% endif %}
    {% if datum %}

         <div class="fakture-lista-naslovna">
    <h2>Ponuda</h2>
    <p>Broj ponude: OF-{{ ponuda.broj_ponude }}-{{ ponuda.datum_ponude|date:'Ymd' }}-{{ ponuda.ident_brojevi }}</p>
         <p>Datum ponude: {{ ponuda.datum_ponude|date:'d-m-Y' }}</p>
         <p>Kupac: {{ ponuda.kupac }}</p>
         <p>Rok plaćanja: {{ ponuda.rok_placanja|date:'d-m-Y' }}</p>
         {% if ponuda.placeno == 'Aktivno' %}
         <p>Realizacija: {{ ponuda.placeno }}</p>
         {% elif ponuda.placeno == 'Stornirano' %}
         <p style="color: darkred; font-size: 20px">Realizacija: {{ ponuda.placeno }}</p>
         {% else %}
          <p style="color: darkgreen; font-size: 20px">Realizacija: {{ ponuda.placeno }}</p>
         {% endif %}
         {% if not prodaja %}
             <p style="font-weight: bold; font-size: 25px; color: darkred">U ponudi nemate unešene usluge!</p>
             <form>
             <button formaction="{% url 'fakture:ponuda-izmjena' ponuda.pk %}">Unesite elemente</button>
             </form>
         {% else %}
             <form>
             <button formaction="{% url 'fakture:ponuda-skica' ponuda.pk %}">Ponuda-skica</button>
             </form>
         {% endif %}
         </div>

{% else %}
<h3>U bazi trenutno nema kreiranih Ponuda!</h3>
{% endif %}
{% endblock %}

{% block faktura_button %}
    <div>
    <p>Kreiraj novu ponudu: </p>
    <form>
        <button formaction="{% url 'fakture:ponuda-create' %}">Kreiraj</button>
    </form>
    <br>
        {% if ponuda.placeno == 'Aktivno' %}
     <form>
        <button formaction="{% url 'fakture:ponuda-u-fakturu' ponuda.pk %}">Pretvori u fakturu</button>
    </form>
    <br>
     <form>
        <button formaction="{% url 'fakture:ponuda-storniranje' ponuda.pk %}">Završi ponudu/storno</button>
    </form>
    {% else %}
    <p style="background-color: #cccccc">Faktura je realizovana kao <span style="font-size: 25px; color: darkred">{{ ponuda.placeno }}</span></p>
    {% endif %}
    </div>
{% endblock %}

nativ1/fakture/templates/fakture/ponuda_godine.html
{% extends 'fakture/base_nativ.html' %}
{% block fakture %}

    <div class="fakture-lista-naslovna">
        <h2>Ponuda za {{ ponuda.model.datum_ponude|date:'Y' }} godinu</h2>
            <ul>
                 {% for p in ponuda  %}
                <li><a href="{% url 'fakture:ponuda-skica' p.pk %}">Broj ponude {{ p.broj_ponude }}</a>;  {{ p.kupac }} -- Datum ponude {{ p.datum_ponude|date:'d-m-Y' }}</li>
                {% endfor %}
            </ul>
    </div>
{% endblock %}
{% block faktura_button %}
    <div>
    <p>Kreiraj novu ponudu: </p>
    <form>
        <button formaction="{% url 'fakture:ponuda-create' %}">Kreiraj</button>
    </form>
    </div>
{% endblock %}

nativ1/fakture/templates/fakture/ponuda_prodaja_detail.html
{% extends 'fakture/base_nativ.html' %}
{% block fakture %}

    <h2>Podaci unešeni u ponudu broj {{ prodajaponuda.ponuda.broj_ponude }}</h2>
    <p>Kupac: {{ prodajaponuda.ponuda.kupac.naziv_firme }}</p>
    <p>Broj ponude: {{ prodajaponuda.ponuda.broj_ponude }}</p>
    <p>Usluga: {{ prodajaponuda.opis_usluge }}</p>
    <p>Pozicija: {{ prodajaponuda.pozicija.naziv_pozicije }} -- Kod: {{ prodajaponuda.pozicija.pos_NSN }}{{ prodajaponuda.pozicija.pos_broj }}</p>
    <p>Neto cijena proizvoda: {{ prodajaponuda.neto_cijena_proizvoda }}</p>
    <p>PDV: {{ prodajaponuda.pdv }} %</p>
    <p>Bruto cijena proizvoda: {{ prodajaponuda.bruto_cijena_proizvoda }}</p>
    <p>Neto cijena: {{ prodajaponuda.neto_cijena }}</p>
    <p>Bruto cijena: {{ prodajaponuda.bruto_cijena }}</p>
    <form action="{% url 'fakture:ponuda-prodaja-izmjena' prodajaponuda.pk %}">
    {% csrf_token %}
    <input type="submit" value="Izmjeni">
    </form>
    <br>
            <form>
        <button formaction="{% url 'fakture:ponuda-prodaja-brisanje' prodajaponuda.pk%}">Izbriši unos?</button>
            </form>
    <br>
        <form>
        <button formaction="{% url 'fakture:ponuda-prodaja' prodajaponuda.ponuda.pk%}">Vrati se bez promjena</button>
            </form>
{% endblock %}

nativ1/fakture/templates/fakture/valute_create.html
{% extends 'fakture/base_nativ.html' %}
{% block fakture %}
    <h2>Unesite elemente u tabelu Valute.</h2>
    <form action="{% url 'fakture:kreiraj-valutu' %}" method="post">
    {% csrf_token %}
        <table>
    {{ form.as_table }}
            </table>
    <input type="submit" value="Spasi valutu">
    </form>
    <br>
    <form>
    <button formaction="{% url 'fakture:index' %}">Vrati na početnu</button>
    </form>

{% endblock %}
{% block valute %}
    {% if valute %}
    <h2>Trenutna vrijednost valuta u odnosu na BAM</h2>
    <ul>
    {% for v in valute %}
        <li>Vrijednost valute {{ v.valute }}: {{ v.vrijednost_valute }}<a href="{% url 'fakture:valute_update' v.pk %}">                Promjeni kurs?</a></li>
    {% endfor %}
    </ul>
    {% endif %}
{% endblock %}